In [24]:
lis=[1,2,3]
def func(lis):
    lis.extend([1,2,3])
    print(lis)
func(lis)
print(lis)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [1]:
! pip install flask

In [5]:
lis

[1, 2, 3, 1, 2, 3]

In [2]:
from flask import Flask, render_template, request

app = Flask(__name__)


@app.route('/form')
def form():
    return render_template('form.html')


@app.route('/data/', methods=['POST', 'GET'])
def data():
    if request.method == 'GET':
        return f"The URL /data is accessed directly. Try going to '/form' to submit form"
    if request.method == 'POST':
        form_data = request.form
        return render_template('data.html', form_data=form_data)


app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


In [5]:
from flask import Flask, request, render_template
 
# Flask constructor
app = Flask(__name__)  
 
# A decorator used to tell the application
# which URL is associated function
@app.route('/', methods =["GET", "POST"])
def gfg():
    if request.method == "POST":
       # getting input with name = fname in HTML form
       first_name = request.form.get("fname")
       # getting input with name = lname in HTML form
       last_name = request.form.get("lname")
       return "Your name is "+first_name + last_name
    return render_template("form.html")
 
if __name__=='__main__':
   app.run(port=3000)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
[2023-05-27 12:49:31,617] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\Yogesh Yadav\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req

In [25]:
from itertools import permutations 

In [46]:
for i in combinations_with_replacement(range(5),3):
    print(i)

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 0, 4)
(0, 1, 1)
(0, 1, 2)
(0, 1, 3)
(0, 1, 4)
(0, 2, 2)
(0, 2, 3)
(0, 2, 4)
(0, 3, 3)
(0, 3, 4)
(0, 4, 4)
(1, 1, 1)
(1, 1, 2)
(1, 1, 3)
(1, 1, 4)
(1, 2, 2)
(1, 2, 3)
(1, 2, 4)
(1, 3, 3)
(1, 3, 4)
(1, 4, 4)
(2, 2, 2)
(2, 2, 3)
(2, 2, 4)
(2, 3, 3)
(2, 3, 4)
(2, 4, 4)
(3, 3, 3)
(3, 3, 4)
(3, 4, 4)
(4, 4, 4)


In [45]:
from itertools import combinations_with_replacement


In [56]:
len([i for i in permutations(range(5),3)])
    

60

In [ ]:
len([i for i in permutations_with_repla(range(5),3)])

In [104]:
from scipy.stats import binom
import numpy as np
n=3
p=0.869
k=np.arange(4)
p=binom.pmf(k,n,p)
p

array([0.00224809, 0.04473873, 0.29677827, 0.65623491])

In [107]:
sum(p[:3])

0.3437650910000001

In [115]:
a=binom.cdf(2,3,0.869)
a

0.34376509099999997

In [75]:
a*args,**kargs):
    s=0
    for i in args:
        s+=i
    print(kargs['Name'],s)
add(1,2,3 , Name='Yogesh')    


Yogesh 6


In [82]:
k=np.arange(3)
k

array([0, 1, 2])

In [76]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [118]:
from scipy.stats import poisson
k=np.arange(6)
rate=3.2
poisson.pmf(k,rate)

array([0.0407622 , 0.13043905, 0.20870248, 0.22261598, 0.17809279,
       0.11397938])

In [2]:
! pip install sketchpy

     ---------------------------------------- 62.0/62.0 kB 3.4 MB/s eta 0:00:00
     ---------------------------------------- 67.4/67.4 kB ? eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 67.1/67.1 kB ? eta 0:00:00
  Created wheel for turtle: filename=turtle-0.0.1-py3-none-any.whl size=22185 sha256=80f8c77268d56b2470f33836d230b915a998c6a63b42af15e0c3925ae2f4c50b
  Stored in directory: c:\users\yogesh yadav\appdata\local\pip\cache\wheels\1a\8b\a8\3def5d06272e9213d7691d137f65864acf0b855c476890874e
Successfully built turtle


In [6]:
from sketchpy import library as lib

In [24]:
obh=lib.ironman_ascii()

In [21]:
obh.Pen()

In [23]:
obh.Canvas

tkinter.Canvas

In [26]:
# import module
from tabulate import tabulate
 
# assign data
mydata = [
    ["Nikhil", "Delhi"],
    ["Ravi", "Kanpur"],
    ["Manish", "Ahmedabad"],
      ["Prince", "Bangalore"]
]
 
# create header
head = ["Name", "City"]
 
# display table
print(tabulate(mydata, headers=head, tablefmt='grid',showindex=True))

TclError: invalid command name ".!canvas"