In [42]:
import tensorflow as tf

inception_net = tf.keras.applications.MobileNetV2()

In [49]:
len(labels)

1001

In [50]:
import requests

# Download human-readable labels for ImageNet.
response = requests.get("https://git.io/JJkYN")
labels = response.text.split("\n")

def classify_image(inp):
  inp = inp.reshape((-1, 224, 224, 3))
  inp = tf.keras.applications.mobilenet_v2.preprocess_input(inp)
  prediction = inception_net.predict(inp).flatten()
  confidences = {labels[i]: float(prediction[i]) for i in range(1000)}
  return confidences

In [51]:
import gradio as gr

gr.Interface(fn=classify_image, 
             inputs=gr.Image(shape=(224, 224)),
             outputs=gr.Label(num_top_classes=10)).launch()

Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.


1/1 [==============================] - 0s 139ms/step


In [45]:
def swap_case(s):
    r=[]
    for i in s:
        if i.isupper():
            i=i.lower()
            r.append(i)
        else:
            i=i.upper()  
            r.append(i)     
    return ''.join(r)

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

In [46]:
def split_and_join(line):
    a=[]
    for i in line.split():
        a.append(i)
    return '-'.join(a)

    
    # write your code here

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

In [47]:
def mutate_string(string, position, character):
    a=list(string)
    print(string)
    a[position]=character
    return ''.join(a)

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

ValueError: not enough values to unpack (expected 2, got 0)

1/1 [==============================] - 2s 2s/step


In [ ]:
def count_substring(string, sub_string):
    count=0
    n=len(sub_string)
    for i in range(len(string)):
        if string[i:n]==sub_string:
            count+=1
        
        n+=1
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

2

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    a=[]
    for i in s.split():
        a.append(str(i).capitalize())

    return ' '.join(a)

if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    print(result)



1 W 2 R 3g


In [ ]:


def wrap(string, max_width):
    for i in range(0,len(string)+1,max_width):
        result = string[i:i+max_width]
        if len(result) == max_width:
            print(result)
        else:
            return(result)
        


if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

'3g'

In [ ]:
import numpy

def arrays(arr):
    arr.reverse()
    arr1=list(map(float,arr))
    a=numpy.array(arr1)
    return a
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]


In [ ]:
import numpy
n,m=[int(i) for i in input().split()]
a=list()
for i in range(n):
    a.append([])
    for j in range(m):
        a[i].append(int(input()))  
a=numpy.array(a)
print(a.T)
print(a.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
import numpy
n,m=[int(i) for i in input().split()]
a=[[int(i) for i in input().split()] for i in range(n)]
a=numpy.array(a)
print(a.T)
print(a.flatten())

[[1, 2], [3, 4]]